[world]
name = "Budokan"
description = "Budokan local dev world"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "budokan"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "evolute_duel"

[env]
chain_id = "KATANA_LOCAL"
rpc_url = "http://localhost:5050/"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x02f808e319783173b7a36bae6ab318fb98f6553fce73786b430cc02110483fd4"  # Uncomment and update this line with your world address.

[writers]
# Tournament
"evolute_duel-Tournament" = ["evolute_duel-tournament_mock"]
"evolute_duel-Registration" = ["evolute_duel-tournament_mock"]
"evolute_duel-Leaderboard" = ["evolute_duel-tournament_mock"]
"evolute_duel-PlatformMetrics" = ["evolute_duel-tournament_mock"]
"evolute_duel-TournamentTokenMetrics" = ["evolute_duel-tournament_mock"]
"evolute_duel-PrizeMetrics" = ["evolute_duel-tournament_mock"]
"evolute_duel-EntryCount" = ["evolute_duel-tournament_mock"]
"evolute_duel-Prize" = ["evolute_duel-tournament_mock"]
"evolute_duel-Token" = ["evolute_duel-tournament_mock"]
"evolute_duel-TournamentConfig" = ["evolute_duel-tournament_mock"]
"evolute_duel-PrizeClaim" = ["evolute_duel-tournament_mock"]
"evolute_duel-QualificationEntries" = ["evolute_duel-tournament_mock"]
# Game
"evolute_duel-GameMetadata" = ["evolute_duel-game_mock"]
"evolute_duel-GameCounter" = ["evolute_duel-game_mock"]
"evolute_duel-SettingsDetails" = ["evolute_duel-game_mock"]
"evolute_duel-SettingsCounter" = ["evolute_duel-game_mock"]
"evolute_duel-Settings" = ["evolute_duel-game_mock"]
"evolute_duel-TokenMetadata" = ["evolute_duel-game_mock"]
"evolute_duel-Score" = ["evolute_duel-game_mock"]


[migration]
order_inits = []
skip_contracts = ["evolute_duel-Budokan"]
