[world]
name = "Realms World"
website = "https://realms.world/"
description = "DNC"
seed = "DNC"

[env]
# account_address = "0x0"
# private_key = "0x0"
chain_id = "SN_SEPOLIA"
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x01bfa92665fb815c9ec5f37c562a5c9a06fdf23ce022c1d33d4ac07cef5ad80c"

[namespace]
default = "evolute_duel"

[writers]
"evolute_duel" = ["evolute_duel-Budokan"]

[init_call_args]
"evolute_duel-Budokan" = [
    "1", # safe_mode
    "0" # test_mode
]

[migration]
order_inits = []
skip_contracts = [
    "evolute_duel-tournament_mock", 
    "evolute_duel-game_mock", 
    "evolute_duel-erc20_mock", 
    "evolute_duel-erc721_mock", 
]