[world]
name = "Realms World"
website = "https://realms.world/"
description = "DNC"
seed = "DNC"

[env]
chain_id = "SN_MAINNET"
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x5c6d0020a9927edca9ddc984b97305439c0b32a1ec8d3f0eaf6291074cc9799"
world_block = 1385480

[namespace]
default = "evolute_duel"

[writers]
"evolute_duel" = ["evolute_duel-Budokan"]

[init_call_args]
"evolute_duel-Budokan" = [
    "0", # safe_mode
    "0" # test_mode
]

[migration]
order_inits = []
skip_contracts = [
    "evolute_duel-tournament_mock", 
    "evolute_duel-game_mock", 
    "evolute_duel-erc20_mock", 
    "evolute_duel-erc721_mock", 
]
